name: CI/CD Pipeline - Docker Test

on:
  push:
    branches:
      - main
      - marcoantonio   # Branch adicional
  pull_request:
    branches:
      - main
      - marcoantonio   # Branch adicional

jobs:
  test:
    name: Testar e Validar Aplicação
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instalar Docker Compose
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 3. Verificar arquivos no diretório backend
      - name: Listar arquivos no diretório backend
        run: ls -l backend

      # 4. Build e execução da aplicação usando Docker Compose
      - name: Build e subir aplicação com Docker Compose
        run: docker-compose -f backend/docker-compose.yml up --build -d

      # 5. Verificar status dos containers
      - name: Verificar status dos containers
        run: docker-compose -f backend/docker-compose.yml ps

      # 6. Testar aplicação com Curl
      - name: Testar aplicação rodando
        run: |
          sleep 20  # Aguarda a aplicação iniciar
          curl -f http://localhost:8080/actuator/health || exit 1

      # 7. Mostrar logs da aplicação (em caso de falha)
      - name: Logs da aplicação
        if: failure()
        run: docker-compose -f backend/docke
