name: CI/CD Pipeline - Testes Automatizados

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Testar e Validar Aplicação
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: estoque_tio_sanduba
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configuração do Java
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Instalar dependências do Maven
      - name: Instalar dependências do Maven
        run: mvn install --file backend/pom.xml

      # 4. Rodar Testes Automatizados do Back-End
      - name: Executar testes automatizados
        run: mvn test --file backend/pom.xml

      # 5. Validar HTML e CSS (Arquivos no caminho correto)
      - name: Validar HTML e CSS
        run: |
          npx html-validator-cli --file backend/src/main/resources/static/index.html
          npx stylelint "backend/src/main/resources/static/**/*.css"

      # 6. Resultado Final
      - name: Resultado dos Testes
        if: failure()
        run: echo "❌ Erro: Pipeline falhou devido a testes que não passaram!"
