name: CI/CD Pipeline - Docker Test

on:
  push:
    branches:
      - main
      - marcoantonio   # Branch adicional
  pull_request:
    branches:
      - main
      - marcoantonio   # Branch adicional

jobs:
  test:
    name: Testar e Validar Aplicação
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instalar Docker Compose
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 3. Build e subir aplicação com Docker Compose
      - name: Build e subir aplicação com Docker Compose
        run: docker-compose -f backend/docker-compose.yml up --build -d

      # 4. Aguardar aplicação iniciar
      - name: Aguarda aplicação iniciar
        run: sleep 20

      # 5. Testar aplicação no endpoint "/produtos"
      - name: Testar aplicação rodando no endpoint "/produtos"
        run: |
          curl -f http://localhost:8080/produtos || exit 1

      # 6. Logs da aplicação em caso de erro
      - name: Logs dos containers
        if: failure()
        run: docker-compose -f backend/docker-compose.yml logs

      # 7. Parar e remover containers
      - name: Parar containers e limpar ambiente
        run: docker-compose -f backend/docker-compose.yml down
