name: CI/CD Pipeline - Docker Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    name: Build e Teste da Aplicação via Docker
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Configurar Docker no ambiente
      - name: Configurar Docker
        run: |
          docker --version
          docker-compose --version

      # 3. Build da Imagem Docker
      - name: Build da imagem Docker
        run: |
          docker build -t backend-app -f Dockerfile .

      # 4. Rodar o container
      - name: Rodar container Docker
        run: |
          docker run -d -p 8080:8080 --name backend-app backend-app

      # 5. Testar se a aplicação está rodando
      - name: Testar aplicação
        run: |
          sleep 10  # Aguarda a aplicação subir
          curl -f http://localhost:8080/actuator/health || exit 1

      # 6. Parar e Remover container
      - name: Parar container
        run: |
          docker stop backend-app
          docker rm backend-app
