name: CI/CD Pipeline - Docker Test

on:
  push:
    branches:
      - main
      - marcoantonio   # Adicione sua branch aqui
  pull_request:
    branches:
      - main
      - marcoantonio   # Adicione sua branch aqui

jobs:
  test:
    name: Testar e Validar Aplicação
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Instalar Docker Compose
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 3. Build da aplicação usando Docker
      - name: Build e execução da aplicação no Docker
        run: docker-compose up --build -d

      # 4. Verificar se a aplicação está rodando
      - name: Verificar status dos containers
        run: docker ps -a

      # 4. Rodar o container
      - name: Rodar container Docker
        run: |
          docker run -d -p 8080:8080 --name backend-app backend-app

      # 5. Testar se a aplicação está rodando
      - name: Testar aplicação
        run: |
          sleep 10  # Aguarda a aplicação subir
          curl -f http://localhost:8080/actuator/health || exit 1

      # 6. Parar e Remover container
      - name: Parar container
        run: |
          docker stop backend-app
          docker rm backend-app
